### ISSUE TITLE
python disparity.py Traceback (most recent call last):   File "disparity.py", line 79, in <module>     h,w = img_2.shape ValueError: too many values to unpack

### ISSUE THREAD

**Issue by jackylee1** [OmarPadierna/3DReconstruction#1]
python disparity.py
Traceback (most recent call last):
  File "disparity.py", line 79, in <module>
    h,w = img_2.shape
ValueError: too many values to unpack

**Comment by OmarPadierna** [comment]
Hi jackylee1. Thanks for pointing this out!. This error happens because when the image is colored, the shape method gives back a size 3 tuple (height,width,channels). I just updated the code to correct this issue. I was originally working with grayscale images when that happens the shape method delivers a tuple of size 2 (height, width). In any case it is fixed now, thanks again! .
