### ISSUE TITLE
(-215:Assertion failed) nimages > 0 in function 'calibrateCameraRO'

### ISSUE THREAD

**Issue by leoregner** [OmarPadierna/3DReconstruction#2]
I am trying to calibrate my iPhone XS camera using 23 picture of the chessboard. However, I am getting the following error message. Could somebody please help me.

Thanks in advance!

```
100%|##########| 23/23 [11:20:43<00:00, 905.60s/it]   
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Image loaded, Analizying...
Traceback (most recent call last):
  File "calibrate.py", line 68, in <module>
    ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points,gray_image.shape[::-1], None, None)
cv2.error: OpenCV(4.0.0) /io/opencv/modules/calib3d/src/calibration.cpp:3679: error: (-215:Assertion failed) nimages > 0 in function 'calibrateCameraRO'
```

**Comment by OmarPadierna** [comment]
The error happens because you don't have enough image points. Due to the following reason: 

The algorithm is looping through every one of your images, but is not able to detect a chessboard (otherwise you would see the message "Chessboard detected!"). Since it is not able to detect a chessboard then the img_points array remains empty and is sent to calibrateCamera function as is. The calibrateCamera function has an internal assertion that prevents you from using it if there are no image points.

The solution is to take more or better pictures. You can check step 3 in the tutorial I wrote: https://medium.com/@omar.ps16/stereo-3d-reconstruction-with-opencv-using-an-iphone-camera-part-ii-77754b58bfe0 

Or you can check this resource: http://aishack.in/tutorials/calibrating-undistorting-opencv-oh-yeah/

In any case the issue is most likely on the way you've taken the pictures rather than with the code itself.

**Comment by leoregner** [comment]
Thanks for your support :)
