### ISSUE TITLE
I have this issue when i lauch disparity.py:

### ISSUE THREAD

**Issue by rudyrim** [OmarPadierna/3DReconstruction#3]
Traceback (most recent call last):
  File "...../disparity.py", line 86, in <module>
    img_1_undistorted = cv2.undistort(img_1, K, dist, None, new_camera_matrix)
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\calib3d\src\undistort.dispatch.cpp:179: error: (-215:Assertion failed) dst.data != src.data in function 'cv::undistort'

**Comment by OmarPadierna** [comment]
The dist parameter (obtained from the calibration script) has data that is different from the image you're using to undistort. This means that most likely you skipped the calibration script, and tried to reconstruct 2 images that you took with the preexisting calibration parameters. OpenCV is telling you that i can't remove distortion because the data in the images is different from the data in the distortion matrix. 

You should first run the calibration.py script and generate your own calibration parameter files, then run the reconstruction algorithm. To do that, follow the tutorial referenced in the readme
